catalogMode: prefer
shellEmulator: true

trustPolicy: no-downgrade

packages:
  - client
overrides:
  vite: npm:vite@8.0.1

catalog:
  '@antfu/eslint-config': ^7.7.3
  '@arethetypeswrong/cli': ^0.18.2
  '@nuxt/content': ^3.12.0
  '@nuxt/devtools-ui-kit': ^3.2.4
  '@nuxt/kit': ^4.4.2
  '@nuxt/module-builder': ^1.0.2
  '@nuxt/schema': ^4.4.2
  '@nuxt/test-utils': ^4.0.0
  '@nuxt/ui': ^4.5.1
  '@nuxtjs/i18n': ^10.2.3
  '@nuxtjs/robots': ^5.7.1
  '@unhead/schema-org': ^2.1.12
  '@vue/test-utils': ^2.4.6
  better-sqlite3: ^12.8.0
  bumpp: ^11.0.1
  cheerio: ^1.2.0
  defu: ^6.1.4
  eslint: ^10.1.0
  eslint-plugin-harlanzw: ^0.10.3
  happy-dom: ^20.8.4
  nuxt: ^4.4.2
  nuxt-site-config: ^3.2.21
  nuxtseo-shared: ^0.1.0
  pkg-types: ^2.3.0
  typescript: ^5.9.3
  vitest: ^4.1.0
onlyBuiltDependencies:
  - '@parcel/watcher'
  - better-sqlite3
  - esbuild
  - vue-demi

trustPolicyIgnoreAfter: 262800
