catalogMode: prefer
minimumReleaseAgeExclude:
  - '@nuxt/ui@4.8.2'
  - '@unhead/schema-org'
  - '@vue/test-utils@2.4.11'
  - unhead
  - '@unhead/bundler'
  - '@unhead/vue'
  - nuxtseo-layer-devtools
  - nuxtseo-shared
  - '@vue/compiler-core@3.5.38'
  - '@vue/compiler-dom@3.5.38'
  - '@vue/compiler-sfc@3.5.38'
  - '@vue/compiler-ssr@3.5.38'
  - '@vue/reactivity@3.5.38'
  - '@vue/runtime-core@3.5.38'
  - '@vue/runtime-dom@3.5.38'
  - '@vue/server-renderer@3.5.38'
  - '@vue/shared@3.5.38'
  - vue@3.5.38
  - nuxt-site-config-kit@4.1.1
  - nuxt-site-config@4.1.1
  - site-config-stack@4.1.1
  - '@nuxt/kit@4.5.0'
  - '@nuxt/nitro-server@4.5.0'
  - '@nuxt/schema@4.5.0'
  - '@nuxt/vite-builder@4.5.0'
  - nuxt@4.5.0
shellEmulator: true

trustPolicy: no-downgrade
packages:
  - devtools
  - '!examples/**'
  - '!test/compat-v2/**'
overrides:
  '@unhead/vue': ^3.2.1
  unhead: ^3.2.1
  vite: npm:vite@8.0.1
  vue: ^3.5.40
catalog:
  '@antfu/eslint-config': ^9.1.0
  '@arethetypeswrong/cli': ^0.18.5
  '@iconify-json/lucide': ^1.2.118
  '@nuxt/content': ^3.15.0
  '@nuxt/kit': ^4.5.0
  '@nuxt/module-builder': ^1.0.2
  '@nuxt/schema': ^4.5.0
  '@nuxt/test-utils': ^4.0.3
  '@nuxt/ui': ^4.10.0
  '@nuxtjs/i18n': ^10.4.1
  '@nuxtjs/robots': ^6.1.2
  '@unhead/schema-org': ^3.2.1
  '@unhead/schema-org-v2': npm:@unhead/schema-org@^2.1.16
  '@vue/test-utils': ^2.4.11
  better-sqlite3: ^12.11.1
  bumpp: ^11.1.0
  cheerio: ^1.2.0
  defu: ^6.1.7
  eslint: ^10.7.0
  eslint-plugin-harlanzw: ^0.17.0
  happy-dom: ^20.10.6
  nuxt: ^4.5.0
  nuxt-site-config: ^4.1.1
  nuxtseo-layer-devtools: ^5.3.2
  nuxtseo-shared: ^5.3.2
  pkg-types: ^2.3.1
  typescript: 6.0.3
  ufo: ^1.6.4
  unbuild: ^3.6.1
  vitest: ^4.1.10
trustPolicyIgnoreAfter: 262800
onlyBuiltDependencies:
  - '@parcel/watcher'
  - better-sqlite3
  - esbuild
  - vue-demi
allowBuilds:
  '@parcel/watcher': true
  better-sqlite3: true
  esbuild: true
  vue-demi: true
