name: CI

on:
  push:
    paths-ignore:
      - '**/README.md'
      - 'docs/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  ci:
    uses: harlan-zw/nuxt-seo/.github/workflows/reusable-ci.yml@226c091a0744b7286ef721ac035eed53856bfaa5
    with:
      migration: true
      playwright: false
      test-command: pnpm test:run
